# Repo: Contoso/BuildTemplates
# File: common.yml
parameters:
  vmImage: 'ubuntu 16.04'
  repositoryName: ''

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - bash: |
    if [ -z "$SOLUTION" ]; then
      echo "##vso[task.logissue type=error;]Missing template parameter \"repositoryName\""
      echo "##vso[task.complete result=Failed;]"
    fi
  env:
    SOLUTION: ${{ parameters.repositoryName }}
  displayName: Check for required parameters
  - script: echo Hello template
  - checkout: ${{ parameters.repositoryName }}
    clean: false
    fetchDepth: 5
    lfs: true
    path: template
  
